#' @title helper: generate a list of all possible resin sample identifiers
#'
#' @description Generates a list of all possible resin sample identifiers.
#' Output is a dataframe with two identical columns, one of which is used
#' expressely for joining to uploaded Lachat files.
#'
#' @export
#'

resinSamplesFrame <- data.frame(
  resinSamples = c(
    'NULL',
    'LDP.LATR1',
    'LDP.LATR2',
    'LDP.IP1',
    'LDP.IP2',
    'LDP.LATR CNTL1',
    'LDP.LATR CNTL2',
    'LDP.LATR CNTL3',
    'LDP.IP CNTL1',
    'LDP.IP CNTL2',
    'LDP.IP CNTL3',
    'UMP.LATR1',
    'UMP.LATR2',
    'UMP.IP1',
    'UMP.IP2',
    'SRR.LATR1',
    'SRR.LATR2',
    'SRR.IP1',
    'SRR.IP2',
    'MCN.LATR1',
    'MCN.LATR2',
    'MCN.IP1',
    'MCN.IP2',
    'MCS.LATR1',
    'MCS.LATR2',
    'MCS.IP1',
    'MCS.IP2',
    'GTW IP1 (Gateway/Thompson)',
    'GTW IP2 (Gateway/Thompson)',
    'LVE IP3 104th&Bell Levytrail',
    'LVE IP4 104th&Bell Levytrail',
    'SME.LATR1',
    'SME.LATR2',
    'SME.IP1',
    'SME.IP2',
    'PWP.LATR1',
    'PWP.LATR2',
    'PWP.IP1',
    'PWP.IP2',
    'MVP_NMP',
    'SMW.LATR1',
    'SMW.LATR2',
    'SMW.IP1',
    'SMW.IP2',
    'SMW.LATR CNTL1',
    'SMW.LATR CNTL2',
    'SMW.LATR CNTL3',
    'SMW.IP CNTL1',
    'SMW.IP CNTL2',
    'SMW.IP CNTL3',
    'DBG.LATR1',
    'DBG.LATR2',
    'DBG.IP1',
    'DBG.IP2',
    'DBG.LATR CNTL1',
    'DBG.LATR CNTL2',
    'DBG.LATR CNTL3',
    'DBG.IP CNTL1',
    'DBG.IP CNTL2',
    'DBG.IP CNTL3',
    'SNE.LATR1',
    'SNE.LATR2',
    'SNE.IP1',
    'SNE.IP2',
    'SNW.LATR1',
    'SNW.LATR2',
    'SNW.IP1',
    'SNW.IP2',
    'EMW.LATR1',
    'EMW.LATR2',
    'EMW.IP1',
    'EMW.IP2',
    'EME.LATR1',
    'EME.LATR2',
    'EME.IP1',
    'EME.IP2',
    'WTM.LATR1',
    'WTM.LATR2',
    'WTM.IP1',
    'WTM.IP2',
    'WTM.LATR CNTL1',
    'WTM.LATR CNTL2',
    'WTM.LATR CNTL3',
    'WTM.IP CNTL1',
    'WTM.IP CNTL2',
    'WTM.IP CNTL3',
    'MCS.IP1.6MONTH',
    'MCS.IP2.6MONTH',
    'DBG.IP1.6MONTH',
    'DBG.IP2.6MONTH',
    'WTM.IP1.6MONTH',
    'WTM.IP2.6MONTH',
    'resin.KCl.1',
    'resin.KCl.2',
    'resin.KCl.3'
    ),
  stringsAsFactors = FALSE
  ) |>
dplyr::mutate(databaseID = resinSamples)
